# Generated by Django 6.0.6 on 2026-08-24 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Numéro')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('partie_contractante', models.CharField(help_text='Nom du fournisseur, client ou prestataire.', max_length=200, verbose_name='Partie contractante')),
                ('type_contrat', models.CharField(choices=[('FOURNISSEUR', 'Contrat fournisseur'), ('CLIENT', 'Contrat client'), ('PRESTATAIRE', 'Prestation de services'), ('BAIL', 'Bail / location'), ('AUTRE', 'Autre')], max_length=20, verbose_name='Type de contrat')),
                ('reference', models.CharField(blank=True, help_text='Numéro de référence du contrat papier, si applicable.', max_length=100, verbose_name='Référence')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_echeance', models.DateField(blank=True, help_text='Laisser vide si le contrat est à durée indéterminée (aucune alerte ne sera envoyée).', null=True, verbose_name="Date d'échéance")),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Montant')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('EXPIRE', 'Expiré'), ('RESILIE', 'Résilié')], default='ACTIF', max_length=10, verbose_name='Statut')),
                ('motif_resiliation', models.TextField(blank=True, verbose_name='Motif de résiliation')),
                ('date_resiliation', models.DateField(blank=True, null=True, verbose_name='Date de résiliation')),
                ('seuils_alertes_envoyes', models.JSONField(blank=True, default=list, help_text="Empêche l'envoi en double des alertes d'échéance (30/15/7/3/1 jours, ou EXPIRE).", verbose_name="Seuils d'alerte déjà notifiés")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats_enregistres', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contrats', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='PieceJointeContrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='contrats/pieces_jointes/%Y/%m/', verbose_name='Fichier')),
                ('nom_original', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('ajoute_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pieces_jointes_contrats', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('contrat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_jointes', to='contrats.contrat', verbose_name='Contrat')),
            ],
            options={
                'verbose_name': 'Pièce jointe de contrat',
                'verbose_name_plural': 'Pièces jointes de contrat',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['filiale', 'statut'], name='contrats_co_filiale_0d72af_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_echeance'], name='contrats_co_date_ec_05fbbd_idx'),
        ),
    ]
