# Generated by Django 6.0.6 on 2026-08-22 00:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        ('salles', '0002_remove_salle_est_salle_groupe_alter_salle_filiale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('type_evenement', models.CharField(choices=[('CEREMONIE', 'Cérémonie'), ('DISCOURS', 'Discours'), ('FETE', 'Fête'), ('RECEPTION', 'Réception'), ('SEMINAIRE', 'Séminaire / Formation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20, verbose_name='Type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateTimeField(verbose_name='Début')),
                ('date_fin', models.DateTimeField(verbose_name='Fin')),
                ('journee_entiere', models.BooleanField(default=False, help_text="Masque les heures à l'affichage (fête, jour férié…).", verbose_name='Journée entière')),
                ('lieu', models.CharField(blank=True, max_length=200, verbose_name='Lieu')),
                ('visibilite', models.CharField(choices=[('GROUPE', 'Tout le groupe'), ('FILIALE', 'La filiale seulement'), ('SERVICE', 'Le service seulement')], default='FILIALE', max_length=20, verbose_name='Visibilité')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='evenements/', verbose_name='Illustration')),
                ('annule', models.BooleanField(default=False, verbose_name='Annulé')),
                ('motif_annulation', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements', to='filiales.filiale', verbose_name='Filiale')),
                ('salle', models.ForeignKey(blank=True, help_text="Si l'événement se tient dans une salle du groupe.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='salles.salle', verbose_name='Salle')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='filiales.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['date_debut'],
                'indexes': [models.Index(fields=['date_debut'], name='evenements__date_de_8064e3_idx'), models.Index(fields=['filiale', 'date_debut'], name='evenements__filiale_8b8ecc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='evenement_fin_apres_debut')],
            },
        ),
    ]
