# Generated by Django 6.0.6 on 2026-08-24 09:23

import applications.galerie.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evenements', '0001_initial'),
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('visibilite', models.CharField(choices=[('GROUPE', 'Tout le groupe'), ('FILIALE', 'La filiale seulement'), ('SERVICE', 'Le service seulement')], default='FILIALE', max_length=20, verbose_name='Visibilité')),
                ('date_evenement', models.DateField(blank=True, help_text='Date à laquelle les photos ont été prises.', null=True, verbose_name="Date de l'événement")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='albums_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('evenement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='evenements.evenement', verbose_name='Événement')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='filiales.filiale', verbose_name='Filiale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='albums', to='filiales.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Album',
                'verbose_name_plural': 'Albums',
                'ordering': ['-date_evenement', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field='hauteur', upload_to=applications.galerie.models._chemin_photo, validators=[applications.galerie.models.valider_taille_image], verbose_name='Image', width_field='largeur')),
                ('miniature', models.ImageField(blank=True, editable=False, null=True, upload_to=applications.galerie.models._chemin_miniature, verbose_name='Vignette')),
                ('legende', models.CharField(blank=True, max_length=255, verbose_name='Légende')),
                ('largeur', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Largeur')),
                ('hauteur', models.PositiveIntegerField(blank=True, editable=False, null=True, verbose_name='Hauteur')),
                ('taille_octets', models.PositiveIntegerField(default=0, editable=False, verbose_name='Taille (octets)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de téléversement')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='galerie.album', verbose_name='Album')),
                ('televersee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='photos_televersees', to=settings.AUTH_USER_MODEL, verbose_name='Téléversée par')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
                'ordering': ['date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['filiale', '-date_creation'], name='galerie_alb_filiale_f823d1_idx'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['album', 'date_creation'], name='galerie_pho_album_i_24f393_idx'),
        ),
    ]
