# Generated by Django 5.2.8 on 2026-06-10 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reunion', models.DateField(verbose_name='Date de réunion')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('liste_presence', models.TextField(verbose_name='Liste de présence')),
                ('precisions', models.TextField(blank=True, verbose_name='Précisions spécifiques')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRMEE', 'Confirmée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('motif_refus', models.TextField(blank=True, verbose_name='Motif du refus')),
                ('date_validation', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='salles.salle', verbose_name='Salle')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_validees', to=settings.AUTH_USER_MODEL, verbose_name='Validée par')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reunion', '-heure_debut'],
            },
        ),
    ]
