# Generated by Django 5.2.8 on 2026-06-10 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
        ('salles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['nom_complet'],
            },
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='liste_presence',
        ),
        migrations.AddField(
            model_name='reservation',
            name='annule_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_annulees', to=settings.AUTH_USER_MODEL, verbose_name='Annulée par'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='date_annulation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='motif_annulation',
            field=models.TextField(blank=True, verbose_name="Motif d'annulation"),
        ),
        migrations.AddField(
            model_name='reservation',
            name='nom_reservant',
            field=models.CharField(default=0, max_length=255, verbose_name='Nom du réservant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='precisions',
            field=models.TextField(blank=True, help_text='Café, boissons, collations, matériel supplémentaire, etc.', verbose_name='Précisions spécifiques'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['salle', 'date_reunion'], name='reservation_salle_i_812d94_idx'),
        ),
        migrations.AddField(
            model_name='participant',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='reservations.reservation', verbose_name='Réservation'),
        ),
    ]
