# Generated by Django 5.2.8 on 2026-06-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_participant_remove_reservation_liste_presence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
    ]
