# Generated by Django 6.0.6 on 2026-06-15 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_participant_options_and_more'),
        ('salles', '0002_remove_salle_est_salle_groupe_alter_salle_filiale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(blank=True, help_text="Récupéré de l'AD en prod si disponible, sinon saisi (EF-03).", max_length=30, verbose_name='Téléphone du réservant'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EN_ATTENTE', 'En attente'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée'), ('DEPLACEE', 'Déplacée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.CreateModel(
            name='SerieRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_reservant', models.CharField(max_length=255, verbose_name='Nom du réservant')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone du réservant')),
                ('frequence', models.CharField(choices=[('QUOTIDIENNE', 'Tous les jours (ouvrés)'), ('HEBDOMADAIRE', 'Chaque semaine'), ('BIHEBDOMADAIRE', 'Une semaine sur deux'), ('MENSUELLE', 'Chaque mois')], default='HEBDOMADAIRE', max_length=20, verbose_name='Fréquence')),
                ('jours_semaine', models.JSONField(blank=True, default=list, help_text="Liste d'entiers 0=lundi … 6=dimanche (pour les fréquences hebdomadaires).", verbose_name='Jours de la semaine')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('date_debut', models.DateField(verbose_name='Date de début de la série')),
                ('date_fin', models.DateField(verbose_name='Date de fin de la série')),
                ('precisions', models.TextField(blank=True, verbose_name='Précisions spécifiques')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_recurrence', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series_recurrence', to='salles.salle', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Série récurrente',
                'verbose_name_plural': 'Séries récurrentes',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='reservation',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='reservations.serierecurrence', verbose_name='Série récurrente'),
        ),
    ]
