# Generated by Django 6.0.6 on 2026-07-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='objet_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Identifiant de l'objet"),
        ),
        migrations.AddField(
            model_name='notification',
            name='objet_type',
            field=models.CharField(blank=True, max_length=60, verbose_name="Type d'objet"),
        ),
    ]
