# Generated by Django 6.0.6 on 2026-06-15 09:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0005_reservation_telephone_alter_reservation_statut_and_more'),
        ('salles', '0002_remove_salle_est_salle_groupe_alter_salle_filiale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=150, verbose_name='Prénom')),
                ('profession', models.CharField(blank=True, max_length=200, verbose_name='Profession')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='Contact (téléphone / email)')),
                ('objet_visite', models.TextField(verbose_name='Objet de la visite')),
                ('statut', models.CharField(choices=[('SAISIE', 'Saisie'), ('ENVOYEE_DG', 'Envoyée au DG'), ('RENVOYEE_SECRETAIRE', 'Renvoyée à la secrétaire'), ('VALIDEE_DG', 'Validée par le DG'), ('CONFIRMEE', 'Confirmée'), ('ANNULEE', 'Annulée'), ('TERMINEE', 'Terminée')], default='SAISIE', max_length=25, verbose_name='Statut')),
                ('date_souhaitee', models.DateField(blank=True, null=True, verbose_name='Date souhaitée')),
                ('heure_debut', models.TimeField(blank=True, null=True, verbose_name='Heure de début')),
                ('heure_fin', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='Date de confirmation')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('dg', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiences_recues', to=settings.AUTH_USER_MODEL, verbose_name='DG destinataire')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audience', to='reservations.reservation', verbose_name='Réservation de salle liée')),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='salles.salle', verbose_name='Salle')),
                ('secretaire', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audiences_saisies', to=settings.AUTH_USER_MODEL, verbose_name='Secrétaire (saisie)')),
            ],
            options={
                'verbose_name': 'Audience',
                'verbose_name_plural': 'Audiences',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='EchangeAudience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='echanges', to='audiences.audience', verbose_name='Audience')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='echanges_audience', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
            ],
            options={
                'verbose_name': "Échange d'audience",
                'verbose_name_plural': "Échanges d'audience",
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Delegation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.TextField(blank=True, help_text="Ex. « Paul s'occupera de recevoir le client ».", verbose_name='Commentaire du DG')),
                ('statut', models.CharField(choices=[('PROPOSEE', 'Proposée'), ('PRISE_EN_COMPTE', 'Prise en compte')], default='PROPOSEE', max_length=20, verbose_name='Statut')),
                ('date_proposition', models.DateTimeField(auto_now_add=True, verbose_name='Date de proposition')),
                ('date_prise_en_compte', models.DateTimeField(blank=True, null=True, verbose_name='Date de prise en compte')),
                ('audience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations', to='audiences.audience', verbose_name='Audience')),
                ('delegue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_recues', to=settings.AUTH_USER_MODEL, verbose_name='Délégué')),
            ],
            options={
                'verbose_name': 'Délégation',
                'verbose_name_plural': 'Délégations',
                'ordering': ['-date_proposition'],
                'constraints': [models.UniqueConstraint(fields=('audience', 'delegue'), name='unique_delegue_par_audience')],
            },
        ),
    ]
