# Generated by Django 6.0.6 on 2026-06-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiences', '0001_initial'),
        ('salles', '0002_remove_salle_est_salle_groupe_alter_salle_filiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='audience',
            name='lieu',
            field=models.CharField(blank=True, help_text='Si pas de salle : ex. « Bureau du DG », « Bureau du délégué ».', max_length=200, verbose_name='Lieu (hors salle)'),
        ),
        migrations.AlterField(
            model_name='audience',
            name='salle',
            field=models.ForeignKey(blank=True, help_text="Optionnel : seulement si l'audience a lieu dans une salle de réunion.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiences', to='salles.salle', verbose_name='Salle'),
        ),
    ]
