# Generated by Django 6.0.6 on 2026-08-30 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Caisse active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('detenteur', models.ForeignKey(blank=True, help_text="Responsable de cette caisse : lui seul l'alimente et la décaisse, avec la direction.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caisses_tenues', to=settings.AUTH_USER_MODEL, verbose_name='Détenteur')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='caisses', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Caisse',
                'verbose_name_plural': 'Caisses',
                'ordering': ['filiale__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='BonSortie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('objet', models.CharField(max_length=255, verbose_name='Objet')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant demandé')),
                ('type_depense', models.CharField(choices=[('TRANSPORT', 'Transport'), ('AUTRE', 'Autre dépense')], default='AUTRE', max_length=20, verbose_name='Type de dépense')),
                ('moyen_transport', models.CharField(blank=True, choices=[('TAXI', 'Taxi'), ('MOTO', 'Moto'), ('GOZEM', 'Gozem')], max_length=20, verbose_name='Moyen de transport')),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='caisse/bons/', verbose_name='Justificatif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', "En attente d'autorisation"), ('AUTORISE', 'Autorisé'), ('REFUSE', 'Refusé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('etape_validation', models.PositiveSmallIntegerField(default=0, verbose_name='Étape de validation')),
                ('motif_decision', models.TextField(blank=True, verbose_name='Motif de la décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('destinataire', models.ForeignKey(blank=True, help_text='Personne qui autorise la dépense. Facultatif pour le transport, qui se paie sans autorisation préalable.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie_a_autoriser', to=settings.AUTH_USER_MODEL, verbose_name='Adressé à')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bons_sortie', to='caisse.caisse', verbose_name='Caisse')),
            ],
            options={
                'verbose_name': 'Bon de sortie',
                'verbose_name_plural': 'Bons de sortie',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='MouvementCaisse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ALIMENTATION', 'Alimentation'), ('SORTIE', 'Sortie de caisse'), ('RETOUR', 'Retour en caisse'), ('CORRECTION', 'Correction')], max_length=20, verbose_name='Type')),
                ('montant', models.DecimalField(decimal_places=2, help_text='Positif pour une entrée, négatif pour une sortie.', max_digits=14, verbose_name='Montant')),
                ('justificatif', models.FileField(blank=True, help_text='Chèque, reçu, capture de transaction.', null=True, upload_to='caisse/justificatifs/', verbose_name='Justificatif')),
                ('reference', models.CharField(blank=True, help_text='Numéro de chèque, référence de virement…', max_length=100, verbose_name='Référence')),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('date_operation', models.DateField(verbose_name="Date de l'opération")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('bon_sortie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='caisse.bonsortie', verbose_name='Bon de sortie')),
                ('caisse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='caisse.caisse', verbose_name='Caisse')),
                ('cree_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_caisse', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
            ],
            options={
                'verbose_name': 'Mouvement de caisse',
                'verbose_name_plural': 'Mouvements de caisse',
                'ordering': ['-date_operation', '-date_creation'],
            },
        ),
        migrations.AddConstraint(
            model_name='caisse',
            constraint=models.UniqueConstraint(fields=('filiale', 'code'), name='caisse_code_unique_par_filiale'),
        ),
        migrations.AddIndex(
            model_name='bonsortie',
            index=models.Index(fields=['caisse', 'statut'], name='caisse_bons_caisse__3fafeb_idx'),
        ),
        migrations.AddIndex(
            model_name='bonsortie',
            index=models.Index(fields=['destinataire', 'statut'], name='caisse_bons_destina_3d9365_idx'),
        ),
        migrations.AddConstraint(
            model_name='bonsortie',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='bon_sortie_montant_positif'),
        ),
        migrations.AddIndex(
            model_name='mouvementcaisse',
            index=models.Index(fields=['caisse', '-date_operation'], name='caisse_mouv_caisse__f69ca4_idx'),
        ),
    ]
