# Generated by Django 6.0.6 on 2026-08-30 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caisse', '0001_initial'),
        ('documents', '0006_alter_configurationdocument_type_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonsortie',
            name='document',
            field=models.OneToOneField(blank=True, editable=False, help_text="Bon de sortie de caisse au format du moteur documentaire, engendré au décaissement pour l'impression et l'archivage.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bon_sortie_caisse', to='documents.document', verbose_name='Pièce imprimable'),
        ),
    ]
