# Generated by Django 6.0.6 on 2026-08-24 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('categorie', models.CharField(choices=[('MATERIEL', 'Matériel'), ('INFORMATIQUE', 'Matériel informatique'), ('FOURNITURES', 'Fournitures de bureau')], max_length=20, verbose_name='Catégorie')),
                ('unite', models.CharField(default='unité', help_text='Ex. pièce, ramette, boîte…', max_length=30, verbose_name='Unité')),
                ('quantite_stock', models.PositiveIntegerField(default=0, editable=False, verbose_name='Quantité en stock')),
                ('seuil_alerte', models.PositiveIntegerField(default=0, help_text='Une notification est envoyée quand le stock descend à ce niveau ou en dessous.', verbose_name="Seuil d'alerte")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=10, verbose_name='Type')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('motif', models.CharField(blank=True, help_text='Ex. « Achat fournisseur X », « Attribution à Y »…', max_length=255, verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='stocks.article', verbose_name='Article')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_stock', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['filiale', 'categorie'], name='stocks_arti_filiale_2522ec_idx'),
        ),
    ]
