# Generated by Django 6.0.6 on 2026-07-22 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse')], max_length=30, verbose_name='Type de document')),
                ('colonnes', models.JSONField(default=list, verbose_name='Colonnes du tableau de lignes')),
                ('visas', models.JSONField(default=list, verbose_name='Chaîne de visas (signatures)')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configurations_document', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Configuration de document',
                'verbose_name_plural': 'Configurations de documents',
                'unique_together': {('filiale', 'type_document')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse')], max_length=30, verbose_name='Type de document')),
                ('numero', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Numéro')),
                ('champs_entete', models.JSONField(blank=True, default=dict, help_text='Champs spécifiques au type de document (ex. fournisseur, département…).', verbose_name="Champs d'en-tête")),
                ('lignes', models.JSONField(blank=True, default=list, verbose_name='Lignes')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Montant total')),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours de validation'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_COURS', max_length=20, verbose_name='Statut')),
                ('etape_visa_courante', models.PositiveIntegerField(default=0, verbose_name='Étape de visa courante')),
                ('historique_visas', models.JSONField(blank=True, default=list, verbose_name='Historique des visas')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to=settings.AUTH_USER_MODEL, verbose_name='Demandeur')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['filiale', 'type_document'], name='documents_d_filiale_dcbc23_idx'), models.Index(fields=['statut'], name='documents_d_statut_ca88e6_idx')],
            },
        ),
    ]
