# Generated by Django 6.0.6 on 2026-08-22 00:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0002_alter_configurationdocument_type_document_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_diffusion', models.DateTimeField(auto_now_add=True, verbose_name='Date de diffusion')),
                ('date_lecture', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_recues', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='documents.document', verbose_name='Note interne')),
            ],
            options={
                'verbose_name': 'Lecture de note interne',
                'verbose_name_plural': 'Lectures de notes internes',
                'ordering': ['-date_diffusion'],
                'indexes': [models.Index(fields=['destinataire', 'date_lecture'], name='notes_lectu_destina_2e91fb_idx')],
                'constraints': [models.UniqueConstraint(fields=('note', 'destinataire'), name='lecture_note_unique_par_destinataire')],
            },
        ),
    ]
