# Generated by Django 6.0.6 on 2026-08-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='piece_jointe',
            field=models.FileField(blank=True, help_text='Facultatif — ex. reçu de parking, facture scannée.', null=True, upload_to='documents/pieces_jointes/%Y/%m/', verbose_name='Pièce jointe (facture, reçu…)'),
        ),
    ]
