# Generated by Django 6.0.6 on 2026-08-24 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_piece_jointe'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_source',
            field=models.ForeignKey(blank=True, help_text="Ex. la Demande d'achat à l'origine d'un Bon de commande.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_derives', to='documents.document', verbose_name='Document source'),
        ),
        migrations.AlterField(
            model_name='configurationdocument',
            name='type_document',
            field=models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse'), ('BON_COMMANDE', 'Bon de commande')], max_length=30, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse'), ('BON_COMMANDE', 'Bon de commande')], max_length=30, verbose_name='Type de document'),
        ),
    ]
