# Generated by Django 6.0.6 on 2026-08-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_configurationdocument_type_document_and_more'),
        ('documents', '0003_document_document_source_and_more'),
    ]

    operations = [
    ]
