# Generated by Django 6.0.6 on 2026-08-24 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_merge_20260824_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationdocument',
            name='type_document',
            field=models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse'), ('BON_COMMANDE', 'Bon de commande'), ('NOTE_INTERNE', 'Note interne')], max_length=30, verbose_name='Type de document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='type_document',
            field=models.CharField(choices=[('FICHE_BESOIN', 'Fiche de besoin'), ('DEMANDE_ACHAT', "Demande d'achat"), ('FICHE_TRANSPORT', 'Fiche de transport'), ('BON_SORTIE_CAISSE', 'Bon de sortie de caisse'), ('BON_COMMANDE', 'Bon de commande'), ('NOTE_INTERNE', 'Note interne')], max_length=30, verbose_name='Type de document'),
        ),
    ]
