# Generated by Django 6.0.6 on 2026-06-15 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salle',
            name='est_salle_groupe',
        ),
        migrations.AlterField(
            model_name='salle',
            name='filiale',
            field=models.ForeignKey(help_text='Filiale qui possède et gère la salle. Ses réservations sont validées par le secrétariat de cette filiale.', on_delete=django.db.models.deletion.PROTECT, related_name='salles', to='filiales.filiale', verbose_name='Filiale propriétaire'),
        ),
    ]
