# Generated by Django 6.0.6 on 2026-08-22 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé de maternité'), ('EXCEPTIONNEL', 'Congé exceptionnel'), ('SANS_SOLDE', 'Congé sans solde')], default='ANNUEL', max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Du')),
                ('date_fin', models.DateField(verbose_name='Au')),
                ('jours_ouvres', models.PositiveSmallIntegerField(default=0, help_text='Calculé à la création : week-ends et jours fériés exclus.', verbose_name='Jours ouvrés décomptés')),
                ('motif', models.TextField(blank=True, verbose_name='Motif')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('date_decision', models.DateTimeField(blank=True, null=True, verbose_name='Date de décision')),
                ('motif_decision', models.TextField(blank=True, verbose_name='Motif de la décision')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes_conge', to=settings.AUTH_USER_MODEL, verbose_name='Salarié')),
                ('valideur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conge_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Validé / refusé par')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('nom', models.CharField(max_length=150, verbose_name='Intitulé')),
                ('filiale', models.ForeignKey(blank=True, help_text='Vide = applicable à tout le groupe.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jours_feries', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Jour férié',
                'verbose_name_plural': 'Jours fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='MouvementConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveSmallIntegerField(verbose_name='Année de rattachement')),
                ('type_mouvement', models.CharField(choices=[('ACQUISITION', 'Acquisition mensuelle'), ('CONSOMMATION', 'Congé pris'), ('RESTITUTION', 'Restitution (annulation)'), ('EXPIRATION', "Solde perdu en fin d'année"), ('CORRECTION', 'Correction manuelle')], max_length=20, verbose_name='Type')),
                ('jours', models.DecimalField(decimal_places=2, help_text='Positif pour un crédit, négatif pour un débit.', max_digits=6, verbose_name='Jours')),
                ('date_effet', models.DateField(verbose_name="Date d'effet")),
                ('motif', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements', to='conges.demandeconge', verbose_name='Demande liée')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements_conge', to=settings.AUTH_USER_MODEL, verbose_name='Salarié')),
            ],
            options={
                'verbose_name': 'Mouvement de congé',
                'verbose_name_plural': 'Mouvements de congé',
                'ordering': ['-date_effet', '-date_creation'],
            },
        ),
        migrations.AddIndex(
            model_name='demandeconge',
            index=models.Index(fields=['utilisateur', 'statut'], name='conges_dema_utilisa_8c4227_idx'),
        ),
        migrations.AddIndex(
            model_name='demandeconge',
            index=models.Index(fields=['date_debut'], name='conges_dema_date_de_c9bdde_idx'),
        ),
        migrations.AddConstraint(
            model_name='demandeconge',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin__gte', models.F('date_debut'))), name='demande_conge_fin_apres_debut'),
        ),
        migrations.AddIndex(
            model_name='jourferie',
            index=models.Index(fields=['date'], name='conges_jour_date_fe5c3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='jourferie',
            constraint=models.UniqueConstraint(fields=('date', 'filiale'), name='jour_ferie_unique_par_date_et_filiale'),
        ),
        migrations.AddIndex(
            model_name='mouvementconge',
            index=models.Index(fields=['utilisateur', 'annee'], name='conges_mouv_utilisa_f6357e_idx'),
        ),
        migrations.AddConstraint(
            model_name='mouvementconge',
            constraint=models.UniqueConstraint(condition=models.Q(('type_mouvement', 'ACQUISITION')), fields=('utilisateur', 'type_mouvement', 'date_effet'), name='une_seule_acquisition_par_mois'),
        ),
    ]
