# Generated by Django 6.0.6 on 2026-08-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='date_evenement',
            field=models.DateField(blank=True, help_text='Date du décès, du mariage, de la naissance… Fait courir le délai de production du justificatif.', null=True, verbose_name="Date de l'évènement"),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='justificatif',
            field=models.FileField(blank=True, help_text="Acte d'état civil ou convocation, à produire sous 8 jours.", null=True, upload_to='conges/justificatifs/', verbose_name='Justificatif'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='motif_permission',
            field=models.CharField(blank=True, help_text='Évènement ouvrant droit à permission (article 45 de la CCIT).', max_length=30, verbose_name='Motif de la permission'),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='type_conge',
            field=models.CharField(choices=[('ANNUEL', 'Congé annuel'), ('PERMISSION', 'Permission exceptionnelle'), ('MALADIE', 'Congé maladie'), ('MATERNITE', 'Congé de maternité'), ('SANS_SOLDE', 'Congé sans solde')], default='ANNUEL', max_length=20, verbose_name='Type de congé'),
        ),
    ]
