# Generated by Django 6.0.6 on 2026-08-30 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0002_demandeconge_date_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='etape_validation',
            field=models.PositiveSmallIntegerField(default=0, help_text='Rang dans le circuit applicable (voir circuits.py).', verbose_name='Étape de validation courante'),
        ),
    ]
