# Generated by Django 6.0.6 on 2026-08-30 20:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conges', '0003_demandeconge_etape_validation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeconge',
            name='date_debut_initiale',
            field=models.DateField(blank=True, editable=False, help_text="Conservée lors d'un report, pour vérifier le plafond de trois mois de l'article 44 de la CCIT.", null=True, verbose_name='Date de départ initialement prévue'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_rappel',
            field=models.DateField(blank=True, help_text='Jour où le salarié a été rappelé pendant son congé.', null=True, verbose_name='Date de rappel en service'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='date_reprise',
            field=models.DateField(blank=True, help_text='Jour où le salarié est reparti en congé après son rappel.', null=True, verbose_name='Date de reprise du congé'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='motif_rappel',
            field=models.TextField(blank=True, verbose_name='Motif du rappel'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='motif_report',
            field=models.TextField(blank=True, verbose_name='Motif du report'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='rappele_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conges_rappeles', to=settings.AUTH_USER_MODEL, verbose_name='Rappelé par'),
        ),
        migrations.AlterField(
            model_name='demandeconge',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('ANNULEE', 'Annulée'), ('INTERROMPUE', 'Interrompue (rappel en service)'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
    ]
