# Generated by Django 6.0.6 on 2026-08-24 08:13

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('client', models.CharField(max_length=200, verbose_name='Client')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date_debut', models.DateField(verbose_name='Début')),
                ('date_fin_prevue', models.DateField(verbose_name='Fin prévue')),
                ('date_fin_reelle', models.DateField(blank=True, null=True, verbose_name='Fin réelle')),
                ('montant', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='Montant')),
                ('statut', models.CharField(choices=[('PLANIFIEE', 'Planifiée'), ('EN_COURS', 'En cours'), ('SUSPENDUE', 'Suspendue'), ('TERMINEE', 'Terminée'), ('ANNULEE', 'Annulée')], default='PLANIFIEE', max_length=20, verbose_name='Statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='filiales.filiale', verbose_name='Filiale')),
                ('intervenants', models.ManyToManyField(blank=True, related_name='prestations', to=settings.AUTH_USER_MODEL, verbose_name='Intervenants')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations_dirigees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestations', to='filiales.service', verbose_name='Service réalisateur')),
            ],
            options={
                'verbose_name': 'Prestation de service',
                'verbose_name_plural': 'Prestations de services',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='JalonPrestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200, verbose_name='Intitulé')),
                ('date_prevue', models.DateField(verbose_name='Date prévue')),
                ('date_realisation', models.DateField(blank=True, null=True, verbose_name='Date de réalisation')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('prestation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jalons', to='prestations.prestation', verbose_name='Prestation')),
            ],
            options={
                'verbose_name': 'Jalon de prestation',
                'verbose_name_plural': 'Jalons de prestation',
                'ordering': ['date_prevue'],
            },
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['service', 'statut'], name='prestations_service_604e40_idx'),
        ),
        migrations.AddIndex(
            model_name='prestation',
            index=models.Index(fields=['filiale', 'date_debut'], name='prestations_filiale_2db385_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestation',
            constraint=models.CheckConstraint(condition=models.Q(('date_fin_prevue__gte', models.F('date_debut'))), name='prestation_fin_prevue_apres_debut'),
        ),
        migrations.AddConstraint(
            model_name='prestation',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gte', 0)), name='prestation_montant_positif'),
        ),
    ]
