# Generated by Django 5.2.8 on 2026-06-10 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom de la salle')),
                ('est_salle_groupe', models.BooleanField(default=False, verbose_name='Salle commune au groupe')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('capacite', models.PositiveIntegerField(verbose_name="Capacité d'accueil")),
                ('equipements', models.JSONField(blank=True, default=list, verbose_name='Équipements disponibles')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='salles/photos/', verbose_name='Photo de la salle')),
                ('active', models.BooleanField(default=True, verbose_name='Salle active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('filiale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Salle',
                'verbose_name_plural': 'Salles',
                'ordering': ['nom'],
            },
        ),
    ]
