# Generated by Django 6.0.6 on 2026-09-07 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('numero_piece', models.CharField(max_length=60, verbose_name="Numéro de pièce d'identité")),
                ('heure_arrivee', models.DateTimeField(auto_now_add=True, verbose_name="Heure d'arrivée")),
                ('heure_depart', models.DateTimeField(blank=True, null=True, verbose_name='Heure de départ')),
                ('enregistre_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites_enregistrees', to=settings.AUTH_USER_MODEL, verbose_name='Enregistré par')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Visite',
                'verbose_name_plural': 'Visites',
                'ordering': ['-heure_arrivee'],
            },
        ),
    ]
