# Generated by Django 6.0.6 on 2026-09-07 10:30

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteurs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='motif',
            field=models.CharField(default='', max_length=255, verbose_name='Motif de la visite'),
        ),
        migrations.AddField(
            model_name='visite',
            name='motif_refus',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Motif du refus'),
        ),
        migrations.AddField(
            model_name='visite',
            name='statut',
            field=models.CharField(choices=[('EN_ATTENTE', 'En attente de validation'), ('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée'), ('TERMINEE', 'Terminée')], default='EN_ATTENTE', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='visite',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visites_traitees', to=settings.AUTH_USER_MODEL, verbose_name='Traité par'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='numero_piece',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^\\d+$', "Le numéro de pièce d'identité ne doit contenir que des chiffres.")], verbose_name="Numéro de pièce d'identité"),
        ),
    ]
