# Generated by Django 6.0.6 on 2026-09-07 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0003_service'),
        ('visiteurs', '0002_visite_motif_visite_motif_refus_visite_statut_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='personne_visitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visites_recues', to=settings.AUTH_USER_MODEL, verbose_name='Personne visitée'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='filiale',
            field=models.ForeignKey(help_text="OSEOR étant un groupe, l'accueil peut recevoir des visiteurs pour n'importe laquelle de ses filiales.", on_delete=django.db.models.deletion.PROTECT, related_name='visites', to='filiales.filiale', verbose_name='Filiale visitée'),
        ),
    ]
