# Generated by Django 6.0.6 on 2026-09-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visiteurs', '0003_visite_personne_visitee_alter_visite_filiale'),
    ]

    operations = [
        migrations.AddField(
            model_name='visite',
            name='type_piece',
            field=models.CharField(choices=[('CNI', "Carte nationale d'identité"), ('PASSEPORT', 'Passeport')], default='CNI', max_length=20, verbose_name='Type de pièce'),
        ),
        migrations.AlterField(
            model_name='visite',
            name='numero_piece',
            field=models.CharField(max_length=30, verbose_name="Numéro de pièce d'identité"),
        ),
    ]
