# Generated by Django 6.0.6 on 2026-06-15 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_alter_participant_date_creation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participant',
            options={'ordering': ['nom', 'prenom'], 'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.RemoveField(
            model_name='participant',
            name='nom_complet',
        ),
        migrations.AddField(
            model_name='participant',
            name='nom',
            field=models.CharField(default='', max_length=150, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='prenom',
            field=models.CharField(blank=True, max_length=150, verbose_name='Prénom'),
        ),
        migrations.AddField(
            model_name='participant',
            name='societe',
            field=models.CharField(blank=True, help_text="Entreprise ou filiale d'origine. Laisser vide pour un participant externe sans société du groupe.", max_length=150, verbose_name="Société / filiale d'appartenance"),
        ),
        migrations.AddField(
            model_name='participant',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AddField(
            model_name='participant',
            name='type_participant',
            field=models.CharField(choices=[('INTERNE', 'Interne (membre du groupe)'), ('EXTERNE', 'Externe')], default='INTERNE', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='participant',
            name='utilisateur',
            field=models.ForeignKey(blank=True, help_text="Renseigné pour un participant interne sélectionné dans l'annuaire (sert à la convocation automatique — RG-13).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur interne lié'),
        ),
    ]
