# Generated by Django 6.0.6 on 2026-06-15 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_reservation_telephone_alter_reservation_statut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='motif',
            field=models.CharField(blank=True, help_text="Objet de la réservation (ex. réunion d'équipe, entretien…).", max_length=255, verbose_name='Motif / objet de la réunion'),
        ),
    ]
