# Generated by Django 6.0.6 on 2026-06-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_reservation_motif'),
    ]

    operations = [
        migrations.AddField(
            model_name='serierecurrence',
            name='motif',
            field=models.CharField(blank=True, max_length=255, verbose_name='Motif / objet de la réunion'),
        ),
    ]
