# Generated by Django 5.2.8 on 2026-06-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_alter_utilisateur_options_remove_utilisateur_actif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='Compte actif'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='derniere_connexion_mobile',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion mobile'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='signature',
            field=models.ImageField(blank=True, help_text='Signature utilisée lors des validations.', null=True, upload_to='utilisateurs/signatures/', verbose_name='Signature électronique'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur Groupe'), ('DIRECTEUR', 'Directeur'), ('CHEF_SERVICE', 'Chef de service'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=30, verbose_name='Rôle'),
        ),
    ]
