# Generated by Django 6.0.6 on 2026-07-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0004_alter_utilisateur_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreLDAP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_uri', models.CharField(blank=True, help_text='Ex. ldap://192.168.1.10 (ou ldaps:// pour le chiffrement TLS).', max_length=255, verbose_name='Adresse du serveur LDAP')),
                ('domaine', models.CharField(blank=True, help_text='Nom NetBIOS du domaine Windows, ex. OSEOR.', max_length=100, verbose_name='Domaine NetBIOS')),
                ('base_dn', models.CharField(blank=True, help_text='Ex. DC=oseor,DC=local', max_length=255, verbose_name='Base DN')),
                ('bind_dn', models.CharField(blank=True, help_text='Ex. CN=svcOseor,OU=Services,DC=oseor,DC=local', max_length=255, verbose_name='DN du compte de service')),
                ('bind_password_chiffre', models.TextField(blank=True, verbose_name='Mot de passe du compte de service (chiffré)')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
            ],
            options={
                'verbose_name': 'Paramètre LDAP',
                'verbose_name_plural': 'Paramètres LDAP',
            },
        ),
    ]
