# Generated by Django 6.0.6 on 2026-08-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0003_service'),
        ('utilisateurs', '0005_parametreldap'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='responsable_hierarchique',
            field=models.ForeignKey(blank=True, help_text='Valide en premier les demandes de cet utilisateur (congés…).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Responsable hiérarchique'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membres', to='filiales.service', verbose_name='Service'),
        ),
    ]
