# Generated by Django 6.0.6 on 2026-08-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0006_utilisateur_responsable_hierarchique_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_naissance',
            field=models.DateField(blank=True, help_text='Alimente les anniversaires du calendrier des événements.', null=True, verbose_name='Date de naissance'),
        ),
    ]
