# Generated by Django 6.0.6 on 2026-08-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0007_utilisateur_date_naissance'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='date_embauche',
            field=models.DateField(blank=True, help_text="Point de départ de l'acquisition des congés (2,5 j/mois). Sans elle, aucun congé n'est acquis.", null=True, verbose_name="Date d'embauche"),
        ),
    ]
