# Generated by Django 6.0.6 on 2026-09-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0008_utilisateur_date_embauche'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur Groupe'), ('DIRECTEUR', 'Directeur'), ('SECRETAIRE', 'Secrétaire / Assistante de direction'), ('CHEF_SERVICE', 'Chef de service'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('EMPLOYE', 'Employé'), ('AGENT_SECURITE', 'Agent de sécurité')], default='EMPLOYE', max_length=30, verbose_name='Rôle'),
        ),
    ]
