# Generated by Django 6.0.6 on 2026-08-30 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet_type', models.CharField(max_length=100, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveIntegerField(verbose_name="Identifiant de l'objet")),
                ('etape_cle', models.CharField(max_length=60, verbose_name="Clé de l'étape")),
                ('etape_libelle', models.CharField(max_length=150, verbose_name='Étape')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name="Rang de l'étape")),
                ('sens', models.CharField(choices=[('VALIDEE', 'Validée'), ('REFUSEE', 'Refusée')], max_length=10, verbose_name='Sens')),
                ('validation_directe', models.BooleanField(default=False, help_text='Décision prise par une autorité supérieure sans attendre les étapes précédentes.', verbose_name='Validation directe')),
                ('etapes_sautees', models.JSONField(blank=True, default=list, verbose_name='Étapes court-circuitées')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('date_decision', models.DateTimeField(auto_now_add=True, verbose_name='Date de la décision')),
                ('acteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='decisions_validation', to=settings.AUTH_USER_MODEL, verbose_name='Décidé par')),
            ],
            options={
                'verbose_name': 'Décision de validation',
                'verbose_name_plural': 'Décisions de validation',
                'ordering': ['objet_type', 'objet_id', 'ordre', 'date_decision'],
                'indexes': [models.Index(fields=['objet_type', 'objet_id'], name='validation__objet_t_ec89ec_idx'), models.Index(fields=['acteur', '-date_decision'], name='validation__acteur__5b48f2_idx')],
            },
        ),
    ]
