# Generated by Django 6.0.6 on 2026-06-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateur_actif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('ADMINISTRATEUR', 'Administrateur Groupe'), ('DIRECTEUR', 'Directeur'), ('SECRETAIRE', 'Secrétaire / Assistante de direction'), ('CHEF_SERVICE', 'Chef de service'), ('COMPTABLE', 'Comptable'), ('RH', 'Ressources Humaines'), ('EMPLOYE', 'Employé')], default='EMPLOYE', max_length=30, verbose_name='Rôle'),
        ),
    ]
