# Generated by Django 6.0.6 on 2026-06-16 05:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text="Code de l'action, ex. RESERVATION_VALIDEE.", max_length=80, verbose_name='Action')),
                ('cible', models.CharField(blank=True, help_text="Description lisible de l'objet concerné.", max_length=255, verbose_name='Cible')),
                ('objet_type', models.CharField(blank=True, max_length=60, verbose_name="Type d'objet")),
                ('objet_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="Identifiant de l'objet")),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Détails')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Horodatage')),
                ('acteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions_journal', to=settings.AUTH_USER_MODEL, verbose_name='Acteur')),
            ],
            options={
                'verbose_name': 'Action journalisée',
                'verbose_name_plural': 'Journal des actions',
                'ordering': ['-date_creation'],
                'indexes': [models.Index(fields=['action'], name='journalisat_action_982692_idx'), models.Index(fields=['objet_type', 'objet_id'], name='journalisat_objet_t_87e4aa_idx')],
            },
        ),
    ]
