# Generated by Django 5.2.8 on 2026-06-10 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreFiliale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delai_min_reservation', models.PositiveIntegerField(default=30, verbose_name='Délai minimum avant réservation (minutes)')),
                ('duree_max_reservation', models.PositiveIntegerField(default=480, verbose_name="Durée maximale d'une réservation (minutes)")),
                ('nb_max_reservations_actives', models.PositiveIntegerField(default=5, verbose_name='Nombre maximum de réservations simultanées')),
                ('delai_annulation', models.PositiveIntegerField(default=60, verbose_name="Délai d'annulation avant début (minutes)")),
                ('filiale', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Paramètre filiale',
                'verbose_name_plural': 'Paramètres filiales',
            },
        ),
    ]
