# Generated by Django 6.0.6 on 2026-08-21 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filiales', '0002_parametrefiliale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, verbose_name='Nom')),
                ('code', models.CharField(max_length=20, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Service actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('chef', models.ForeignKey(blank=True, help_text='Responsable du service. Fait autorité pour les validations.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_diriges', to=settings.AUTH_USER_MODEL, verbose_name='Chef de service')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='filiales.filiale', verbose_name='Filiale')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['filiale__nom', 'nom'],
                'constraints': [models.UniqueConstraint(fields=('filiale', 'code'), name='service_code_unique_par_filiale')],
            },
        ),
    ]
