# Generated by Django 6.0.6 on 2026-08-30 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filiales', '0003_service'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureDisciplinaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Référence')),
                ('faits', models.TextField(verbose_name='Faits reprochés')),
                ('date_faits', models.DateField(verbose_name='Date des faits')),
                ('date_preuve', models.DateField(help_text="Point de départ du délai de deux mois de l'article 58.", verbose_name="Date d'établissement de la preuve")),
                ('qualification', models.CharField(choices=[('FAUTE_SIMPLE', 'Faute professionnelle'), ('FAUTE_LOURDE', 'Faute lourde')], default='FAUTE_SIMPLE', max_length=20, verbose_name='Qualification')),
                ('faute_lourde_invoquee', models.CharField(blank=True, choices=[('REFUS_TRAVAIL', "Refus d'exécuter un travail relevant de l'emploi"), ('VIOLATION_PRESCRIPTION', "Violation caractérisée d'une prescription de service"), ('MALVERSATION', 'Malversation'), ('VOIES_DE_FAIT', "Voies de fait commises dans les locaux de l'établissement"), ('SECRET_PROFESSIONNEL', 'Violation du secret professionnel'), ('IVRESSE', "État d'ivresse caractérisé")], help_text="Énumération de l'article 58. La liste n'étant pas limitative, un cas non listé se décrit dans les faits.", max_length=40, verbose_name='Faute lourde invoquée')),
                ('statut', models.CharField(choices=[('OUVERTE', 'Ouverte'), ('EXPLICATIONS_DEMANDEES', 'Explications demandées'), ('EXPLICATIONS_FOURNIES', 'Explications fournies'), ('SANCTIONNEE', 'Sanction prononcée'), ('CLASSEE', 'Classée sans suite')], default='OUVERTE', max_length=30, verbose_name='Statut')),
                ('mise_a_pied_conservatoire', models.BooleanField(default=False, help_text="Mesure d'attente, le temps d'instruire. N'est pas une sanction et ne préjuge d'aucune.", verbose_name='Mise à pied conservatoire')),
                ('date_mise_a_pied', models.DateField(blank=True, null=True, verbose_name='Début de la mise à pied conservatoire')),
                ('motif_classement', models.TextField(blank=True, verbose_name='Motif du classement')),
                ('date_ouverture', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ouverture")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('filiale', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_disciplinaires', to='filiales.filiale', verbose_name='Filiale')),
                ('ouverte_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_ouvertes', to=settings.AUTH_USER_MODEL, verbose_name='Ouverte par')),
                ('salarie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procedures_disciplinaires', to=settings.AUTH_USER_MODEL, verbose_name='Salarié concerné')),
            ],
            options={
                'verbose_name': 'Procédure disciplinaire',
                'verbose_name_plural': 'Procédures disciplinaires',
                'ordering': ['-date_ouverture'],
            },
        ),
        migrations.CreateModel(
            name='ExplicationSalarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('ECRITE', 'Écrites'), ('VERBALE', 'Verbales, consignées'), ('REFUS', "Le salarié a refusé de s'expliquer")], default='ECRITE', max_length=20, verbose_name='Mode')),
                ('contenu', models.TextField(blank=True, verbose_name='Teneur des explications')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='discipline/explications/', verbose_name='Pièce jointe')),
                ('delegue_present', models.BooleanField(default=False, verbose_name="Salarié assisté d'un délégué du personnel")),
                ('date_explication', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('consignee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='explications_consignees', to=settings.AUTH_USER_MODEL, verbose_name='Consignée par')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explications', to='discipline.proceduredisciplinaire', verbose_name='Procédure')),
            ],
            options={
                'verbose_name': 'Explications du salarié',
                'verbose_name_plural': 'Explications des salariés',
                'ordering': ['date_explication'],
            },
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_sanction', models.CharField(choices=[('AVERTISSEMENT', 'Avertissement avec inscription au dossier'), ('MISE_A_PIED', 'Mise à pied de 1 à 8 jours avec privation de salaire'), ('MISE_A_PIED_AGGRAVEE', 'Mise à pied aggravée de 1 à 15 jours avec privation de salaire'), ('LICENCIEMENT_PREAVIS', 'Licenciement avec préavis'), ('LICENCIEMENT_SANS_PREAVIS', 'Licenciement sans préavis (faute lourde)')], max_length=40, verbose_name='Sanction')),
                ('duree_jours', models.PositiveSmallIntegerField(blank=True, help_text="Pour les mises à pied : 1 à 8 jours, 1 à 15 en cas d'aggravation.", null=True, verbose_name='Durée (jours)')),
                ('motif', models.TextField(verbose_name='Motivation de la sanction')),
                ('date_prononce', models.DateField(verbose_name='Date du prononcé')),
                ('date_notification', models.DateField(blank=True, null=True, verbose_name='Signifiée au salarié le')),
                ('date_inspection_travail', models.DateField(blank=True, help_text="L'article 58 impose d'adresser ampliation de la décision à l'Inspecteur du Travail du ressort.", null=True, verbose_name="Ampliation à l'Inspection du Travail le")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('procedure', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sanction', to='discipline.proceduredisciplinaire', verbose_name='Procédure')),
                ('prononcee_par', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sanctions_prononcees', to=settings.AUTH_USER_MODEL, verbose_name='Prononcée par')),
            ],
            options={
                'verbose_name': 'Sanction disciplinaire',
                'verbose_name_plural': 'Sanctions disciplinaires',
                'ordering': ['-date_prononce'],
            },
        ),
        migrations.AddIndex(
            model_name='proceduredisciplinaire',
            index=models.Index(fields=['salarie', '-date_ouverture'], name='discipline__salarie_88efa8_idx'),
        ),
        migrations.AddIndex(
            model_name='proceduredisciplinaire',
            index=models.Index(fields=['statut'], name='discipline__statut_754034_idx'),
        ),
    ]
