# Generated by Django 6.0.6 on 2026-08-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntreeAide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('RESERVATIONS', 'Réservations de salles'), ('AUDIENCES', 'Audiences'), ('DOCUMENTS', 'Documents administratifs'), ('CONGES', 'Congés'), ('CONTRATS', 'Contrats'), ('PRESTATIONS', 'Prestations de services'), ('STOCKS', 'Gestion de stocks'), ('NOTES', 'Notes internes'), ('UTILISATEURS', 'Utilisateurs et administration'), ('GENERAL', 'Général')], max_length=20, verbose_name='Module')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('mots_cles', models.CharField(help_text='Mots ou expressions séparés par des virgules, utilisés pour retrouver cette réponse.', max_length=500, verbose_name='Mots-clés')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('ordre', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Entrée d'aide",
                'verbose_name_plural': "Entrées d'aide",
                'ordering': ['module', 'ordre'],
            },
        ),
    ]
